title: Dark Data Zine # Title of site.
timezone: America/New_York
desc: Parsons MFADT Dark Data Zine Spring 2021
baseurl: /mfadt-darkdata-zine
# mfadt.parsons.edu/darkdata/2021/

sass:
  sass_dir: _sass
  style: :compressed

permalink: :title

markdown: kramdown

kramdown:
  input: GFM
  html_to_native: true
  syntax_highlighter: rouge

defaults:
  - scope:
      type: "posts"
    values:
      layout: "article"

exclude: ["README.md"]